{
 "title": "Async Service Monitoring",
 "tags": [
  "k8s",
  "augury",
  "async"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "service",
    "query": "frontend,apigateway,backend,autocomplete,feature-switcher,feeds,file-server,insights-handler,iot-service,media-generator,messages,microservice-anomalies,microservice-algo-features,oauth2,reports,algo-anomalies"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"$service-.*\"}[5m])) / min(kube_deployment_status_replicas_available{deployment=\"$service\"})",
     "legendFormat": "{{$service}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{pod_name=~\"$service.*\",container_name!=\"POD\",image!=\"\"})",
     "legendFormat": "{{$service}}"
    }
   ]
  },
  {
   "title": "Event Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nsq_task_latency_distribution_count{service=~\"$service\"}[2m])) by (nsq_channel, nsq_event_name), 0.001)",
     "legendFormat": "{{nsq_event_name}}, {{nsq_channel}}"
    }
   ]
  },
  {
   "title": "Event Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nsq_task_status_count_total{service=~\"$service\",nsq_status=\"FAILED\"}[2m])) by (service) / sum(rate(nsq_task_status_count_total{service=~\"$service\"}[2m])) by (service)",
     "legendFormat": "{{nsq_event_name}}, {{nsq_channel}}"
    }
   ]
  },
  {
   "title": "5 Slowest Service Async Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5, avg(nsq_task_latency_distribution_sum{service=\"$service\"} / nsq_task_latency_distribution_count{service=\"$service\"}) by (nsq_channel, nsq_event_name))",
     "legendFormat": "{{nsq_event_name}}, {{nsq_channel}}"
    }
   ]
  }
 ]
}