{
 "title": "Scylla / I/O",
 "tags": [
  "scylla",
  "2019.1"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "by", "label": "by", "query": "Cluster,DC,Instance,Shard" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(scylla_reactor_utilization, cluster)"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster|$^\", dc=~\"$dc\"}, instance)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "label_values(scylla_reactor_utilization,shard)"
   },
   {
    "name": "classes",
    "label": "classes",
    "query": "label_values(scylla_io_queue_delay,class)"
   },
   { "name": "adhoc", "label": "ad hoc" },
   { "name": "scylla_dash_version", "query": "2019.1" },
   { "name": "monitoring_version", "query": "master" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "<img src=\"http://www.scylladb.com/wp-content/uploads/logo-scylla-white-simple.png\" height=\"70\">\n<hr style=\"border-top: 3px solid #5780c1;\">"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">I/O Queue Information</h1>"
  },
  { "title": "$classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "classes" },
  {
   "title": "$classes I/O Queue delay by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_delay{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "$classes I/O Queue bandwidth by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_bytes{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "$classes I/O Queue IOPS by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  }
 ]
}