{
 "title": "Scylla / Manager Metrics",
 "tags": [
  "1.3",
  "scylla"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "by", "label": "by", "query": "Host,Shard,Keyspace,Cluster" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(scylla_manager_cluster_cql_rtt_ms, cluster)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values(scylla_manager_cluster_cql_rtt_ms{cluster=~\"$cluster|$^\"}, host)"
   },
   {
    "name": "keyspace",
    "label": "keyspace",
    "query": "label_values(scylla_manager_repair_segments_total{host=~\"$host\"}, keyspace)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "label_values(scylla_manager_repair_segments_total, shard)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "content": "<img src=\"http://www.scylladb.com/wp-content/uploads/logo-scylla-white-simple.png\" height=\"70\">&nbsp;<span style=\"font-weight:bold; font-size:40px\">Manager</span>&nbsp;<span style=\"font-size:40px\"> [[cluster]]</span>\n<hr style=\"border-top: 3px solid #5780c1;\">"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"scylla-manager\"}==0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"scylla-manager\", cluster=~\"$cluster|$^\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "No CQL connectivity",
   "type": "singlestat",
   "description": "The number of nodes that Scylla manager CQL probe failed connecting to. It could indicate a network or a node problem",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scylla_manager_healthcheck_cql_status{cluster=~\"$cluster|$^\"}==-1) OR vector(0)",
     "legendFormat": "Nodes without CQL connection"
    }
   ]
  },
  {
   "title": "Active Repair Tasks",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(scylla_manager_task_active_count{cluster=~\"$cluster|$^\", type=\"repair\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Repair progress",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(scylla_manager_repair_progress{cluster=~\"[[cluster]]\", host=~\"$host\", keyspace=\"$keyspace\"}) by (task) * sum(scylla_manager_task_active_count{cluster=~\"[[cluster]]\"}) by (task))"
    }
   ]
  },
  {
   "title": "Repair Segments Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_manager_repair_segments_success{cluster=~\"[[cluster]]\", keyspace=\"$keyspace\", host=~\"$host\", shard=~\"$shard\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Repair Segments Error Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_manager_repair_segments_error{cluster=~\"[[cluster]]\", host=~\"$host\", keyspace=\"$keyspace\", shard=~\"$shard\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "SSH open connections by $by",
   "type": "graph",
   "description": "The number of SSH connection used by the manager",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_manager_ssh_open_streams_count{host=~\"$host\"}) by ($by)"
    }
   ]
  },
  {
   "title": "CQL probe duration by $by",
   "type": "graph",
   "description": "Avrage duration time for a CQL ping operation",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(scylla_manager_cluster_cql_rtt_ms{host=~\"$host\", cluster=~\"[[cluster]]\"}) by ($by)"
    }
   ]
  }
 ]
}