{
 "title": "Scylla / Overview Metrics",
 "tags": [
  "3.0",
  "scylla"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "by", "label": "by", "query": "Cluster,DC,Instance,Shard" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(scylla_reactor_utilization, cluster)"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster|$^\", dc=~\"$dc\"}, instance)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "label_values(scylla_reactor_utilization,shard)"
   },
   { "name": "dash_version", "query": "3-0" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "content": "<img src=\"http://www.scylladb.com/wp-content/uploads/logo-scylla-white-simple.png\" height=\"70\">\n<hr style=\"border-top: 3px solid #5780c1;\">"
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"prometheus-scylladb\", endpoint=\"metrics\", cluster=~\"$cluster|$^\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"prometheus-scylladb\", endpoint=\"metrics\", cluster=~\"$cluster|$^\"}==0) OR vector(0)",
     "legendFormat": "Unreachable"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 6, "x": 4, "y": 6 }, "content": "##  " },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 } },
  {
   "title": "Load",
   "type": "graph",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])"
    }
   ]
  },
  {
   "title": "Requests Served",
   "type": "graph",
   "description": "Amount of requests served as the coordinator. Imbalances here represent dispersion at the client-side level or connection balancing level, not your data model.",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_transport_requests_served{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]]) + sum(irate(scylla_thrift_served{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Average write latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_write_latency_sum{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]])/(sum(rate(scylla_storage_proxy_coordinator_write_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]]) + 1)"
    }
   ]
  },
  {
   "title": "95th percentile write latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "99th percentile write latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "Average read latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_storage_proxy_coordinator_read_latency_sum{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]])/(sum(rate(scylla_storage_proxy_coordinator_read_latency_count{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]]) + 1)"
    }
   ]
  },
  {
   "title": "95th percentile read latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]], le))"
    }
   ]
  },
  {
   "title": "99th percentile read latency by [[by]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]], le))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 30 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Reads and Writes</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 30 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Timeouts and Errors</h1>"
  },
  {
   "title": "Foreground Writes",
   "type": "graph",
   "description": "Foreground writes are writes that weren't acknowledged yet to the application. For instance, if a single replica responded and two are needed due to the consistency level. This metric represents a queue size, not a rate. High values here correlate with increased write latencies.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_foreground_writes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Foreground Reads",
   "type": "graph",
   "description": "Foreground reads are reads that weren't acknowledged yet to the application. For instance, if a single replica responded and two are needed due to the consistency level. This metric represents a queue size, not a rate. High values here correlate with increased read latencies.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_foreground_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Write Timeouts",
   "type": "graph",
   "description": "Requests that Scylla tried to write but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_write_timeouts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Write Unavailable",
   "type": "graph",
   "description": "Requests that Scylla did not even try to write because replicas that were needed to execute this write were unavailable. Unavailable writes are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_write_unavailable{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Background Writes",
   "type": "graph",
   "description": "Background writes are writes that are already acknowledged to the application but have additional work to be done. For instance, if a replica responded and only one is needed, this request is still listed as a background request until all replicas respond. This metric represents a queue size, not a rate. High values here correlate with increased write latencies.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_background_writes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Background Reads",
   "type": "graph",
   "description": "Background reads are reads that are already acknowledged to the application but have additional work to be done. For instance, if a replica responded and only one is needed, this request is still listed as a background request until all replicas respond. This metric represents a queue size, not a rate. High values here correlate with increased read latencies.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Queue Length" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_background_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Read Timeouts",
   "type": "graph",
   "description": "Requests that Scylla tried to read but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_read_timeouts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Read Unavailable",
   "type": "graph",
   "description": "Requests that Scylla did not even try to read because replicas that were needed to execute this write were unavailable. Unavailable reads are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_storage_proxy_coordinator_read_unavailable{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 44 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cache</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 44 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Materialized Views</h1>"
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "description": "Number of rows that were read from the cache, without needing to be fetched from storage.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_row_hits{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "description": "Number of rows that were not present in the cache, and had to be fetched from storage.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cache_row_misses{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[30s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "View Update Backlog",
   "type": "graph",
   "description": "Size in bytes of the view update backlog at each base replica.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_database_view_update_backlog{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Dropped View Updates",
   "type": "graph",
   "description": "Number of dropped view updates due to an excessive view update backlog.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_database_dropped_view_updates{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"}[30s])) by ([[by]])"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 18, "x": 0, "y": 52 } },
  {
   "title": "Throttled Base Writes",
   "type": "graph",
   "description": "Currently throttled base writes, as a consequence of the respective view update backlog.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_storage_proxy_coordinator_current_throttled_base_writes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]|$^\"})  by ([[by]])"
    }
   ]
  }
 ]
}