{
 "title": "Scylla / CQL",
 "tags": [
  "scylla",
  "2019.1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "by", "label": "by", "query": "Cluster,DC,Instance,Shard" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(scylla_reactor_utilization, cluster)"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(scylla_reactor_utilization{cluster=~\"$cluster|$^\", dc=~\"$dc\"}, instance)"
   },
   {
    "name": "shard",
    "label": "shard",
    "query": "label_values(scylla_reactor_utilization,shard)"
   },
   { "name": "adhoc", "label": "ad hoc" },
   { "name": "scylla_dash_version", "query": "2019.1" },
   { "name": "monitoring_version", "query": "master" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "<img src=\"http://www.scylladb.com/wp-content/uploads/logo-scylla-white-simple.png\" height=\"70\">\n<hr style=\"border-top: 3px solid #5780c1;\">"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CQL - Coordinator</h1>"
  },
  {
   "title": "CQL Insert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_inserts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[300s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "CQL Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[300s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "CQL Deletes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_deletes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[300s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "CQL Updates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_updates{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[300s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Client CQL connections by [[by]]",
   "type": "graph",
   "description": "amount of CQL connections currently established",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_transport_current_connections{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "CQL Batches by [[by]]",
   "type": "graph",
   "description": "Number of CQL batches command, each batched command is counted once",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cql_batches{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[300s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "CQL Command In Batches by [[by]]",
   "type": "graph",
   "description": "Number of CQL command batched. Each batch would add the number of commands inside the batch",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_statements_in_batches{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[300s])) by ([[by]])"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 }, "content": "<span/>" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Optimization</h1>"
  },
  {
   "title": "CQL Non-Prepared Statements",
   "type": "gauge",
   "description": "All of the requests should be prepared\n\nPrepared statements remove the overhead of parsing the query every time and allow optimal routing of requests from client to server",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "floor(100 *sum(rate(scylla_query_processor_statements_prepared{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) /(sum(rate(scylla_cql_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) + sum(rate(scylla_cql_inserts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) + sum(rate(scylla_cql_updates{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) + sum(rate(scylla_cql_deletes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL Non-Prepared Statements",
   "type": "graph",
   "description": "All of the requests should be prepared\n",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 20 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_query_processor_statements_prepared{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Non-Paged CQL Reads",
   "type": "gauge",
   "description": "All requests should be paged\n\nNon Paged request sources:\n- Client modifying the fetch size\n\nNon Paged requests require reading all the results and returning them in a single request.",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "100 * (sum(rate(scylla_cql_unpaged_select_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]))/sum(rate(scylla_cql_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "Non-Paged CQL Reads",
   "type": "graph",
   "description": "Non-Paged requests require reading all the results and returning them in a single request",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_unpaged_select_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Non-Token Aware",
   "type": "gauge",
   "description": "All of the requests should be Token Aware\n\nNon Token Aware requests sources:\n* Non-Prepared Stamements\n* Client not using a Token Aware load balancing policy\n\nTokenAware requests are sent to a Scylla node that is also a replica. Token Un-Aware requests require extra hop and additional processing.\n\nNote that the metric shows incorrect values when batches are used.",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "100 - floor(100*(sum(rate(scylla_storage_proxy_coordinator_reads_local_node{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) +sum(rate(scylla_storage_proxy_coordinator_total_write_attempts_local_node{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])))/(sum(rate(scylla_cql_inserts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]) + rate(scylla_cql_updates{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]) + rate(scylla_cql_deletes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]) + rate(scylla_cql_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "Non-Token Aware Queries",
   "type": "graph",
   "description": "Requests that are not token aware indicates that requests are not routed to the right node, which require extra hop and additional processing.\n\nNote that the metric shows incorrect values when batches are used.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]]) - sum(irate(scylla_storage_proxy_coordinator_reads_local_node{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]]) + sum(irate(scylla_cql_inserts{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]) + irate(scylla_cql_updates{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]) + irate(scylla_cql_deletes{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]]) - sum(irate(scylla_storage_proxy_coordinator_total_write_attempts_local_node{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])\n"
    }
   ]
  },
  {
   "title": "Reversed CQL Reads",
   "type": "gauge",
   "description": "Reversed CQL Reads entail additional processing on server side\n\nSources: CQL Read requests with ORDER BY that is different from the \"CLUSTERING ORDER BY\" of the table\nAlternatives:\n\n* Denormalize your data (use a Materialized View)",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "100 * sum(rate(scylla_cql_reverse_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) / sum(rate(scylla_cql_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "Reversed CQL Reads",
   "type": "graph",
   "description": "Reversed CQL Reads entail additional processing on server side and should be avoided",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 26 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_reverse_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Reads",
   "type": "gauge",
   "description": "ALLOW FILTERING CQL Reads, the percentage of read requests with 'ALLOW FILTERING'\n\nALLOW FILTERING CQL Reads entail additional processing on server side\n\nSources: CQL Read requests with \"ALLOW FILTERING\"\n\nALLOW FILTERING should be used when large parts of the filtered data is returned - check \n\"ALLOW FILTERING CQL Read Filtered Rows to check what percentage of the data is used\"\n\nAlternatives:\n- Use a Secondary Index\n- Denormalize your data (use a Materialized View)",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "100 * sum(rate(scylla_cql_filtered_read_requests{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) / sum(rate(scylla_cql_reads{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Reads",
   "type": "graph",
   "description": "Read requests with ALLOW FILTERING\n\nALLOW FILTERING CQL Reads entail additional processing on server side and should be avoided",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 26 },
   "yaxes": [
    { "format": "si:reads/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_filtered_read_requests{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING Filtered Rows",
   "type": "gauge",
   "description": "ALLOW FILTERING Filtered rows, the percentage of rows that were read and then filtered.\n\nALLOW FILTERING CQL Reads entail additional processing on server side. \nReading a row and then filter it is a waste of resources.\n\nSources: CQL Read requests with \"ALLOW FILTERING\"\n\nALLOW FILTERING should be used when large parts of the filtered data is returned\n\nAlternatives:\n- Use a Secondary Index\n- Denormalize your data (use a Materialized View)",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "100 * sum(rate(scylla_cql_filtered_rows_dropped_total{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]))  /sum(rate(scylla_cql_filtered_rows_read_total{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Read Filtering",
   "type": "graph",
   "description": "CQL Queries with ALLOW FILTERING should be avoided.\nDropped rows are rows that were read but were filtered by the server.\nWhen dropped rows is relatively high you should consider the alternatives",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "si:reads/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_filtered_rows_read_total{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])",
     "legendFormat": "rows read $node $shard"
    },
    {
     "expr": "sum(irate(scylla_cql_filtered_rows_matched_total{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])",
     "legendFormat": "rows matched $node $shard"
    },
    {
     "expr": "sum(irate(scylla_cql_filtered_rows_dropped_total{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) by ([[by]])",
     "legendFormat": "rows dropped $node $shard"
    }
   ]
  },
  {
   "title": "CQL ANY Queries",
   "type": "gauge",
   "description": "Using consistency level ANY in a query may hurt persistency, if the node receiving the request will fail the data may be lost",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\", consistency_level=\"ANY\"}[60s]))/sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL ANY CL Queries",
   "type": "graph",
   "description": "Using consistency level ANY in a query may hurt persistency, if the node receiving the request will fail the data may be lost",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 32 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\",  consistency_level=\"ANY\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "CQL ALL CL Queries",
   "type": "gauge",
   "description": "Using consistency level ALL in a query may hurt availability, if a node is unavailable operations will fail",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\", consistency_level=\"ALL\"}[60s]))/sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL ALL CL Queries",
   "type": "graph",
   "description": "Using consistency level ALL in a query may hurt availability, if a node is unavailable operations will fail",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\",  consistency_level=\"ALL\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cross DC Information</h1>"
  },
  {
   "title": "CQL ONE Queries",
   "type": "gauge",
   "description": "Using consistency level ONE in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_ONE instead",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\", consistency_level=\"ONE\"}[60s]))/sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL ONE CL Queries",
   "type": "graph",
   "description": "Using consistency level ONE in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_ONE instead",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 40 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\",  consistency_level=\"ONE\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "CQL QUORUM CL Queries",
   "type": "gauge",
   "description": "Using consistency level QUORUM in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_QUORUM instead",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\", consistency_level=\"QUORUM\"}[60s]))/sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL QUORUM CL Queries",
   "type": "graph",
   "description": "Using consistency level QUORUM in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_QUORUM instead",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 40 },
   "yaxes": [
    { "format": "si:ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\",  consistency_level=\"QUORUM\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Cross DC read requests $dc",
   "type": "gauge",
   "description": "Cross DC traffic may cause additional latencies and network loads and in most cases, should be avoided.\n\nCross DC Read requests sources:\n- Consistency Level that is not LOCAL_XXX\n- Tables with read_repair_chance > 0\n\nNote:\n- If requests are supposed to be  DC local - verify client is using a DCAware policy and a LOCAL_XX consistency level",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 46 },
   "repeat": "dc",
   "targets": [
    {
     "expr": "100*(sum(rate(scylla_storage_proxy_coordinator_reads_remote_node{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) - sum(rate(scylla_storage_proxy_coordinator_reads_remote_node{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", datacenter=~\"$dc\", shard=~\"[[shard]]\"}[60s])))/sum(rate(scylla_storage_proxy_coordinator_reads_remote_node{instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[60s])) OR vector(0)"
    }
   ]
  }
 ]
}