{
 "title": "Service Monitoring",
 "tags": [
  "k8s",
  "augury"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "service", "label": "service", "query": "backend" }
  ]
 },
 "panels": [
  {
   "title": "CPU Avg",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"$service-.*\"}[5m])) / min(kube_deployment_status_replicas_available{deployment=\"$service\"})",
     "legendFormat": "{{$service}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{pod_name=~\"$service.*\",container_name!=\"POD\",image!=\"\"})",
     "legendFormat": "{{$service}}"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(opencensus_io_http_server_request_count{service=~\"$service\"}[2m])) by (service), 0.001)",
     "legendFormat": "{{$service }}"
    }
   ]
  },
  {
   "title": "Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(opencensus_io_http_server_response_count_by_status_code{service=~\"$service\",http_status!~\"[4-5].*\"}[2m])) by (service) / sum(rate(opencensus_io_http_server_request_count{service=~\"$service\"}[2m])) by (service)",
     "legendFormat": "{{ $service }}"
    }
   ]
  },
  {
   "title": "5 Slowest Service API's",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5, (sum(opencensus_io_http_server_latency_sum{pod=~\"$service-.*\"} / opencensus_io_http_server_latency_count{pod=~\"$service-.*\"}) by (http_server_route)))"
    }
   ]
  }
 ]
}